# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='User',
            field=models.ImageField(default='none', upload_to='Post/'),
        ),
    ]
